{*******************************************************************************
  Unit Name: TOML.Tests.NestedKeys
  Purpose: DUnitX tests for TOML v1.0.0 nested key and array-of-tables compliance

  Author: Generated by Claude Code
  Created: 2026-03-20

  Copyright (c) 1984-2026 GTR mbH

  Description:
    Tests parser dotted key nesting, implicit table merging, serializer path
    tracking for [[array]] headers, sub-tables within array elements, and
    round-trip compliance with the TOML v1.0.0 specification.

  Dependencies:
    - DUnitX.TestFramework
    - TOML, TOML.Types, TOML.Parser, TOML.Serializer
*******************************************************************************}
unit TOML.Tests.NestedKeys;

interface

uses
  DUnitX.TestFramework,
  System.SysUtils,
  TOML,
  TOML.Types;

type
  /// <summary>
  /// Tests for TOML v1.0.0 nested key and array-of-tables compliance.
  /// Covers parser dotted keys, implicit table merging, serializer path
  /// tracking, and round-trip correctness.
  /// </summary>
  [TestFixture]
  TTOMLNestedKeyTests = class
  published
    { Parser: dotted key nesting }

    [Test]
    procedure DottedKey_TwoParts_CreatesNestedTable;

    [Test]
    procedure DottedKey_ThreeParts_CreatesDeepNestedTable;

    [Test]
    procedure DottedKey_SharedPrefix_MergesIntoSameTable;

    [Test]
    procedure DottedKey_ThreeLevelMerge_MergesCorrectly;

    [Test]
    procedure DottedKey_DuplicateLeaf_RaisesError;

    [Test]
    procedure DottedKey_InInlineTable_CreatesNestedStructure;

    [Test]
    procedure DottedKey_QuotedSegment_CreatesNestedWithLiteralKey;

    { Serializer: nested arrays of tables }

    [Test]
    procedure Serialize_NestedArrayOfTables_EmitsFullPath;

    [Test]
    procedure Serialize_SubTableUnderArrayElement_EmitsSingleBracketPath;

    [Test]
    procedure Serialize_DeepNesting_EmitsAllLevels;

    { Round-trip tests }

    [Test]
    procedure RoundTrip_CanonicalFruitsExample_PreservesStructure;

    [Test]
    procedure RoundTrip_DeepNestedArrayChains_PreservesStructure;
  end;

implementation

{ TTOMLNestedKeyTests - Parser dotted key tests }

procedure TTOMLNestedKeyTests.DottedKey_TwoParts_CreatesNestedTable;
var
  doc: TTOMLTable;
  value: TTOMLValue;
begin
  doc := ParseTOML('physical.color = "red"');
  try
    Assert.IsTrue(doc.TryGetValue('physical', value), 'physical table should exist');
    Assert.AreEqual(Ord(tvtTable), Ord(value.ValueType), 'physical should be a table');
    Assert.IsTrue(value.AsTable.TryGetValue('color', value), 'color should exist');
    Assert.AreEqual('red', value.AsString);
  finally
    doc.Free;
  end;
end;

procedure TTOMLNestedKeyTests.DottedKey_ThreeParts_CreatesDeepNestedTable;
var
  doc: TTOMLTable;
  value: TTOMLValue;
begin
  doc := ParseTOML('a.b.c = 42');
  try
    Assert.IsTrue(doc.TryGetValue('a', value), 'a should exist');
    Assert.IsTrue(value.AsTable.TryGetValue('b', value), 'b should exist');
    Assert.IsTrue(value.AsTable.TryGetValue('c', value), 'c should exist');
    Assert.AreEqual(Int64(42), value.AsInteger);
  finally
    doc.Free;
  end;
end;

procedure TTOMLNestedKeyTests.DottedKey_SharedPrefix_MergesIntoSameTable;
var
  doc: TTOMLTable;
  value, physicalValue: TTOMLValue;
begin
  doc := ParseTOML(
    'physical.color = "red"' + sLineBreak +
    'physical.shape = "round"'
  );
  try
    Assert.IsTrue(doc.TryGetValue('physical', physicalValue), 'physical should exist');
    Assert.IsTrue(physicalValue.AsTable.TryGetValue('color', value), 'color should exist');
    Assert.AreEqual('red', value.AsString);
    Assert.IsTrue(physicalValue.AsTable.TryGetValue('shape', value), 'shape should exist');
    Assert.AreEqual('round', value.AsString);
  finally
    doc.Free;
  end;
end;

procedure TTOMLNestedKeyTests.DottedKey_ThreeLevelMerge_MergesCorrectly;
var
  doc: TTOMLTable;
  value: TTOMLValue;
begin
  doc := ParseTOML(
    'a.b.x = 1' + sLineBreak +
    'a.b.y = 2' + sLineBreak +
    'a.c = 3'
  );
  try
    Assert.IsTrue(doc.TryGetValue('a', value), 'a should exist');
    Assert.IsTrue(value.AsTable.TryGetValue('b', value), 'b should exist');
    Assert.IsTrue(value.AsTable.TryGetValue('x', value), 'x should exist');
    Assert.AreEqual(Int64(1), value.AsInteger);

    // Re-navigate for y
    doc.TryGetValue('a', value);
    value.AsTable.TryGetValue('b', value);
    Assert.IsTrue(value.AsTable.TryGetValue('y', value), 'y should exist');
    Assert.AreEqual(Int64(2), value.AsInteger);

    // Check c
    doc.TryGetValue('a', value);
    Assert.IsTrue(value.AsTable.TryGetValue('c', value), 'c should exist');
    Assert.AreEqual(Int64(3), value.AsInteger);
  finally
    doc.Free;
  end;
end;

procedure TTOMLNestedKeyTests.DottedKey_DuplicateLeaf_RaisesError;
begin
  Assert.WillRaise(
    procedure
    var
      doc: TTOMLTable;
    begin
      doc := ParseTOML(
        'physical.color = "red"' + sLineBreak +
        'physical.color = "blue"'
      );
      doc.Free;
    end,
    ETOMLParserException
  );
end;

procedure TTOMLNestedKeyTests.DottedKey_InInlineTable_CreatesNestedStructure;
var
  doc: TTOMLTable;
  value, pointValue, xValue: TTOMLValue;
begin
  doc := ParseTOML('point = { x.y = 1, x.z = 2 }');
  try
    Assert.IsTrue(doc.TryGetValue('point', pointValue), 'point should exist');
    Assert.IsTrue(pointValue.AsTable.TryGetValue('x', xValue), 'x should exist');
    Assert.IsTrue(xValue.AsTable.TryGetValue('y', value), 'y should exist');
    Assert.AreEqual(Int64(1), value.AsInteger);
    Assert.IsTrue(xValue.AsTable.TryGetValue('z', value), 'z should exist');
    Assert.AreEqual(Int64(2), value.AsInteger);
  finally
    doc.Free;
  end;
end;

procedure TTOMLNestedKeyTests.DottedKey_QuotedSegment_CreatesNestedWithLiteralKey;
var
  doc: TTOMLTable;
  value: TTOMLValue;
begin
  doc := ParseTOML('valid."dotted.key" = "value"');
  try
    Assert.IsTrue(doc.TryGetValue('valid', value), 'valid table should exist');
    Assert.IsTrue(value.AsTable.TryGetValue('dotted.key', value),
      '"dotted.key" should exist as literal key');
    Assert.AreEqual('value', value.AsString);
  finally
    doc.Free;
  end;
end;

{ TTOMLNestedKeyTests - Serializer tests }

procedure TTOMLNestedKeyTests.Serialize_NestedArrayOfTables_EmitsFullPath;
var
  doc: TTOMLTable;
  fruits, varieties: TTOMLArray;
  fruitTable, varietyTable: TTOMLTable;
  tomlStr: string;
  parsedDoc: TTOMLTable;
  value: TTOMLValue;
begin
  doc := TTOMLTable.Create;
  try
    fruits := TTOMLArray.Create;

    // First fruit with varieties
    fruitTable := TTOMLTable.Create;
    fruitTable.Add('name', TTOMLString.Create('apple'));
    varieties := TTOMLArray.Create;
    varietyTable := TTOMLTable.Create;
    varietyTable.Add('name', TTOMLString.Create('red delicious'));
    varieties.Add(varietyTable);
    varietyTable := TTOMLTable.Create;
    varietyTable.Add('name', TTOMLString.Create('granny smith'));
    varieties.Add(varietyTable);
    fruitTable.Add('varieties', varieties);
    fruits.Add(fruitTable);

    // Second fruit with one variety
    fruitTable := TTOMLTable.Create;
    fruitTable.Add('name', TTOMLString.Create('banana'));
    varieties := TTOMLArray.Create;
    varietyTable := TTOMLTable.Create;
    varietyTable.Add('name', TTOMLString.Create('plantain'));
    varieties.Add(varietyTable);
    fruitTable.Add('varieties', varieties);
    fruits.Add(fruitTable);

    doc.Add('fruits', fruits);

    tomlStr := SerializeTOML(doc);

    Assert.IsTrue(Pos('[[fruits]]', tomlStr) > 0, 'Should contain [[fruits]]');
    Assert.IsTrue(Pos('[[fruits.varieties]]', tomlStr) > 0,
      'Should contain [[fruits.varieties]]');

    // Round-trip verify
    parsedDoc := ParseTOML(tomlStr);
    try
      Assert.IsTrue(parsedDoc.TryGetValue('fruits', value), 'fruits should exist');
      Assert.AreEqual(2, value.AsArray.Count, 'Should have 2 fruits');
      value.AsArray.GetItem(0).AsTable.TryGetValue('varieties', value);
      Assert.AreEqual(2, value.AsArray.Count, 'First fruit should have 2 varieties');
    finally
      parsedDoc.Free;
    end;
  finally
    doc.Free;
  end;
end;

procedure TTOMLNestedKeyTests.Serialize_SubTableUnderArrayElement_EmitsSingleBracketPath;
var
  doc: TTOMLTable;
  fruits: TTOMLArray;
  fruitTable, physicalTable: TTOMLTable;
  tomlStr: string;
  parsedDoc: TTOMLTable;
  value: TTOMLValue;
begin
  doc := TTOMLTable.Create;
  try
    fruits := TTOMLArray.Create;

    fruitTable := TTOMLTable.Create;
    fruitTable.Add('name', TTOMLString.Create('apple'));
    physicalTable := TTOMLTable.Create;
    physicalTable.Add('color', TTOMLString.Create('red'));
    physicalTable.Add('shape', TTOMLString.Create('round'));
    fruitTable.Add('physical', physicalTable);
    fruits.Add(fruitTable);

    doc.Add('fruits', fruits);

    tomlStr := SerializeTOML(doc);

    Assert.IsTrue(Pos('[[fruits]]', tomlStr) > 0, 'Should contain [[fruits]]');
    Assert.IsTrue(Pos('[fruits.physical]', tomlStr) > 0,
      'Should contain [fruits.physical]');
    Assert.AreEqual(0, Pos('[[fruits.physical]]', tomlStr),
      'Should NOT contain [[fruits.physical]]');

    // Round-trip
    parsedDoc := ParseTOML(tomlStr);
    try
      parsedDoc.TryGetValue('fruits', value);
      value.AsArray.GetItem(0).AsTable.TryGetValue('physical', value);
      Assert.AreEqual('red', value.AsTable.Items['color'].AsString);
    finally
      parsedDoc.Free;
    end;
  finally
    doc.Free;
  end;
end;

procedure TTOMLNestedKeyTests.Serialize_DeepNesting_EmitsAllLevels;
var
  doc, cTable: TTOMLTable;
  aArray, bArray, cArray: TTOMLArray;
  aTable, bTable: TTOMLTable;
  tomlStr: string;
  parsedDoc: TTOMLTable;
  value: TTOMLValue;
begin
  doc := TTOMLTable.Create;
  try
    aArray := TTOMLArray.Create;
    aTable := TTOMLTable.Create;
    aTable.Add('val', TTOMLInteger.Create(1));

    bArray := TTOMLArray.Create;
    bTable := TTOMLTable.Create;
    bTable.Add('val', TTOMLInteger.Create(10));

    cArray := TTOMLArray.Create;
    cTable := TTOMLTable.Create;
    cTable.Add('val', TTOMLInteger.Create(100));
    cArray.Add(cTable);

    bTable.Add('c', cArray);
    bArray.Add(bTable);
    aTable.Add('b', bArray);
    aArray.Add(aTable);
    doc.Add('a', aArray);

    tomlStr := SerializeTOML(doc);

    Assert.IsTrue(Pos('[[a]]', tomlStr) > 0, 'Should contain [[a]]');
    Assert.IsTrue(Pos('[[a.b]]', tomlStr) > 0, 'Should contain [[a.b]]');
    Assert.IsTrue(Pos('[[a.b.c]]', tomlStr) > 0, 'Should contain [[a.b.c]]');

    // Round-trip
    parsedDoc := ParseTOML(tomlStr);
    try
      parsedDoc.TryGetValue('a', value);
      Assert.AreEqual(1, value.AsArray.Count, 'a should have 1 element');
      value.AsArray.GetItem(0).AsTable.TryGetValue('b', value);
      Assert.AreEqual(1, value.AsArray.Count, 'b should have 1 element');
      value.AsArray.GetItem(0).AsTable.TryGetValue('c', value);
      Assert.AreEqual(1, value.AsArray.Count, 'c should have 1 element');
      Assert.AreEqual(Int64(100), value.AsArray.GetItem(0).AsTable.Items['val'].AsInteger);
    finally
      parsedDoc.Free;
    end;
  finally
    doc.Free;
  end;
end;

{ TTOMLNestedKeyTests - Round-trip tests }

procedure TTOMLNestedKeyTests.RoundTrip_CanonicalFruitsExample_PreservesStructure;
var
  tomlInput, serialized: string;
  doc, parsedDoc: TTOMLTable;
  value, subValue: TTOMLValue;
  fruits: TTOMLArray;
begin
  // The canonical example from the TOML v1.0.0 spec
  tomlInput :=
    '[[fruits]]' + sLineBreak +
    'name = "apple"' + sLineBreak +
    '' + sLineBreak +
    '[fruits.physical]' + sLineBreak +
    'color = "red"' + sLineBreak +
    'shape = "round"' + sLineBreak +
    '' + sLineBreak +
    '[[fruits.varieties]]' + sLineBreak +
    'name = "red delicious"' + sLineBreak +
    '' + sLineBreak +
    '[[fruits.varieties]]' + sLineBreak +
    'name = "granny smith"' + sLineBreak +
    '' + sLineBreak +
    '[[fruits]]' + sLineBreak +
    'name = "banana"' + sLineBreak +
    '' + sLineBreak +
    '[[fruits.varieties]]' + sLineBreak +
    'name = "plantain"';

  doc := ParseTOML(tomlInput);
  try
    // Verify parsed structure
    Assert.IsTrue(doc.TryGetValue('fruits', value), 'fruits should exist');
    fruits := value.AsArray;
    Assert.AreEqual(2, fruits.Count, 'Should have 2 fruits');

    // First fruit
    Assert.IsTrue(fruits.GetItem(0).AsTable.TryGetValue('name', value));
    Assert.AreEqual('apple', value.AsString);
    Assert.IsTrue(fruits.GetItem(0).AsTable.TryGetValue('physical', value));
    Assert.IsTrue(value.AsTable.TryGetValue('color', subValue));
    Assert.AreEqual('red', subValue.AsString);
    Assert.IsTrue(fruits.GetItem(0).AsTable.TryGetValue('varieties', value));
    Assert.AreEqual(2, value.AsArray.Count, 'Apple should have 2 varieties');

    // Second fruit
    Assert.IsTrue(fruits.GetItem(1).AsTable.TryGetValue('name', value));
    Assert.AreEqual('banana', value.AsString);
    Assert.IsTrue(fruits.GetItem(1).AsTable.TryGetValue('varieties', value));
    Assert.AreEqual(1, value.AsArray.Count, 'Banana should have 1 variety');

    // Serialize
    serialized := SerializeTOML(doc);

    Assert.IsTrue(Pos('[[fruits]]', serialized) > 0, 'Serialized should have [[fruits]]');
    Assert.IsTrue(Pos('[fruits.physical]', serialized) > 0,
      'Serialized should have [fruits.physical]');
    Assert.IsTrue(Pos('[[fruits.varieties]]', serialized) > 0,
      'Serialized should have [[fruits.varieties]]');

    // Round-trip: parse the serialized output
    parsedDoc := ParseTOML(serialized);
    try
      Assert.IsTrue(parsedDoc.TryGetValue('fruits', value), 'RT fruits should exist');
      Assert.AreEqual(2, value.AsArray.Count, 'RT should have 2 fruits');
      Assert.IsTrue(
        value.AsArray.GetItem(0).AsTable.TryGetValue('physical', subValue),
        'RT first fruit should have physical');
      Assert.IsTrue(
        value.AsArray.GetItem(0).AsTable.TryGetValue('varieties', subValue),
        'RT first fruit should have varieties');
      Assert.AreEqual(2, subValue.AsArray.Count, 'RT apple should have 2 varieties');
    finally
      parsedDoc.Free;
    end;
  finally
    doc.Free;
  end;
end;

procedure TTOMLNestedKeyTests.RoundTrip_DeepNestedArrayChains_PreservesStructure;
var
  tomlInput, serialized: string;
  doc, parsedDoc: TTOMLTable;
  value: TTOMLValue;
begin
  tomlInput :=
    '[[a]]' + sLineBreak +
    'val = 1' + sLineBreak +
    '' + sLineBreak +
    '[[a.b]]' + sLineBreak +
    'val = 10' + sLineBreak +
    '' + sLineBreak +
    '[[a.b.c]]' + sLineBreak +
    'val = 100' + sLineBreak +
    '' + sLineBreak +
    '[[a.b.c]]' + sLineBreak +
    'val = 101' + sLineBreak +
    '' + sLineBreak +
    '[[a]]' + sLineBreak +
    'val = 2' + sLineBreak +
    '' + sLineBreak +
    '[[a.b]]' + sLineBreak +
    'val = 30';

  doc := ParseTOML(tomlInput);
  try
    Assert.IsTrue(doc.TryGetValue('a', value), 'a should exist');
    Assert.AreEqual(2, value.AsArray.Count, 'a should have 2 elements');

    // a[0].b[0].c has 2 entries
    value.AsArray.GetItem(0).AsTable.TryGetValue('b', value);
    Assert.AreEqual(1, value.AsArray.Count, 'a[0].b should have 1 element');
    value.AsArray.GetItem(0).AsTable.TryGetValue('c', value);
    Assert.AreEqual(2, value.AsArray.Count, 'a[0].b[0].c should have 2 elements');

    // Serialize and round-trip
    serialized := SerializeTOML(doc);

    Assert.IsTrue(Pos('[[a]]', serialized) > 0, 'Should contain [[a]]');
    Assert.IsTrue(Pos('[[a.b]]', serialized) > 0, 'Should contain [[a.b]]');
    Assert.IsTrue(Pos('[[a.b.c]]', serialized) > 0, 'Should contain [[a.b.c]]');

    parsedDoc := ParseTOML(serialized);
    try
      Assert.IsTrue(parsedDoc.TryGetValue('a', value), 'RT a should exist');
      Assert.AreEqual(2, value.AsArray.Count, 'RT a should have 2 elements');
      value.AsArray.GetItem(0).AsTable.TryGetValue('b', value);
      value.AsArray.GetItem(0).AsTable.TryGetValue('c', value);
      Assert.AreEqual(2, value.AsArray.Count, 'RT c should have 2 elements');
    finally
      parsedDoc.Free;
    end;
  finally
    doc.Free;
  end;
end;

initialization
  TDUnitX.RegisterTestFixture(TTOMLNestedKeyTests);

end.
